### ISSUE TITLE
Styles only get inlined if <!-- juice.inject --> is present

### ISSUE THREAD

**Issue by thasmo** [IngenuityDesign/gulp-juice-concat#2]
Currently when there's no placement comment `<!-- juice.inject -->` no styles get inlined at all. It would be nice if styles get inlined even if the placement comment is not present.

**Comment by webmakersteve** [comment]
Sure thing. I'll take a look at this and fix it so the styles will get inlined even if no external css is used. That was the intention so working otherwise is a bug.

**Comment by thasmo** [comment]
Cool! The behavior I'm looking for, i.e. which I have a use-case for is that all CSS gets inlined independent of the `<!-- juice.inject -->` tag - it must not be present. But if it is present, all CSS which has not been inlined (media-queries, etc.) should get embedded using a `style` element at the position of the `<!-- juice.inject -->` tag.

Does that make sense to you?

**Comment by webmakersteve** [comment]
I think this should be fixed with the most recent commit.

**Comment by thasmo** [comment]
I've read the updated docs. Does that mean I can't use Gulp's stream workflow to pipe in Sass files, convert them to CSS and pipe them directly to gulp-juice-concat anymore? I was looking for a gulp plugin which was able to process CSS files on the go without the need of writing them to the filesystem before - which this plugin did. But now it seems this has changed, right?

**Comment by webmakersteve** [comment]
Interesting point. Kinda went right over my head that that functionality
would be overriden with the change.

Let me make another update to it for the use case you've got. I'm a big fan
of the virtual files (Vinyl) in gulp so I've got an idea that will do both
of those two things.

On Tue, Sep 8, 2015 at 5:56 PM, Thomas Deinhamer notifications@github.com
wrote:

> I've read the updated docs. Does that mean I can't use Gulp's stream
> workflow to pipe in Sass files, convert them to CSS and pipe them directly
> to gulp-juice-concat anymore? I was looking for a gulp plugin which was
> able to process CSS files on the go without the need of writing them to the
> filesystem before - which this plugin did. But now it seems this has
> changed, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IngenuityDesign/gulp-juice-concat/issues/2#issuecomment-138715639
> .

## 

_Stephen M. Parente_
Technical Lead & Co-Founder
_91ferns Web Development, LLC_

*m: *(914) 943-8239

"Code is poetry" - the Wordpress Project

πάντα δι' αὐτοῦ ἐγένετο, καὶ χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἕν. ὃ γέγονεν ἐν αὐτῷ
ζωὴ ἦν, καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων: καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει,
καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν.

**Comment by webmakersteve** [comment]
What I'm going to do is cache the Vinyl objects that have been preprocessed. Would you mind showing me your implementation? Because piping both types of files throws an error in the node-sass library. 

If i see how you're doing it I can give it the best of both worlds.

**Comment by webmakersteve** [comment]
Check it out now.
